### PR TITLE
Fix point_from_bytes accepting out-of-range pubkeys and add test vector

### PR DESCRIPTION
**Pull request by jonasnick**
Without this PR `point_from_bytes` wrongly accepts pubkeys greater than the field size. Also added test case (for increasing line coverage only unfortunately). Based on #116

### CODE REVIEW

**Comment by elichai** [comment]
Ping https://github.com/sipa/bips/pull/74

**Comment by jonasnick** [comment]
@elichai in what way?

**Comment by elichai** [comment]
@jonasnick I just saw the `based on #116`. my mistake. it's related to that. not this.

**Comment by sipa** [comment]
Rebased version: https://github.com/sipa/bips/tree/nickler_add-test-vector

**Comment by jonasnick** [comment]
Thanks @sipa. Rebased.

**Comment by jonasnick** [comment]
rebased

**Comment by sipa** [comment]
Also update `test-vectors.csv`?

**Comment by jonasnick** [comment]
Also update `test-vectors.csv`!

**Comment by sipa** [comment]
ACK

**Pull request merged**
