### PR TITLE
remove redundant check

### PR DESCRIPTION
**Pull request by fametrano**
why checking that r<p ? For any invalid r, signature would fail anyway. Am I missing something?

The provided test cases support that the check is redundant; if it is not, then it might be worth providing a dedicated test case if possible.

Instead, s is checked to avoid malleability, if I got it right...

### CODE REVIEW

**Comment by fametrano** [comment]
It should not matter, nor even if r is not reduced

**Comment by real-or-random** [comment]
Yeah okay, I think it depends.

If the "≠" operator is meant to implement inequality on ordinary integers and not inequality on field elments, the current pseudocode only makes sense if `x(R)` is reduced because otherwise the verification may reject valid signatures. And a reduced `x(R)` will always compare unequal to an `r` for which `r >= p`. So if `x(R)` is reduced, then the check is indeed not necessary. 

If the "≠" operator implements inequality on field elements instead, then either choice (having the check or dropping the check) should give you a secure and correct signature scheme. However, if we drop the check, the the resulting signature scheme has valid signatures (with high `r`) that honest implementations will never generate. This is not an immediate problem but an uncommon property that I would like to avoid.

**Comment by jonasnick** [comment]
`x(R)` returns a coordinate which are in `[0,p)`, so they are always reduced (`x(P) and y(P) refer to the X and Y coordinates of a point P` and `curve with equation y2 = x3 + 7 over the integers modulo p`.).

I'd say leave as is because
1. There may be implementations which (wrongly) use field inequality instead of integer inequality in the `x(R) !=r` check. Without this PR they won't accept sigs that correct implementations reject. Yes, it's hard to generate a point with a "reducable" x-coordinate.
2. consistency with batch verification
3. maintains (unmentioned) invariant that all defined variables are actually field/group elements

**Comment by real-or-random** [comment]
I think independent of whether the check is good to have or not, we should clarify that x(R) is reduced, and what the semantics of "≠" are. I can do that.

**Comment by fametrano** [comment]
not sure I do understand @jonasnick's answer.

Here we have no `x(R)` and no `x(R) !=r`: `r` comes from `int_from_bytes(sig[0:32])` so all we know is that it is a 32 bytes integer. It is unnecessary to ensure that `r<p`: the check is a waste for a valid sig and an invalid `r>=p` sig would fail anyway.

This is also true for batch verification: I'm going to edit the spec accordingly.

**Comment by jonasnick** [comment]
> Not sure I do understand @jonasnick's answer, especially the "Without this PR they won't accept sigs that correct implementations reject" part.

If someone implements `x(R) != r` as `x(R) != r % p` (python notation) they may accept a signature with `r > p` which a correct implemention (without modulo in the inequality check) wouldn't have accepted.

> This is also true for batch verification: I'm going to edit the spec accordingly.
In batch verification explicitly rejecting `r > p` is essential otherwise `R<sub>i</sub> = (r, y)` is not well defined.

**Comment by real-or-random** [comment]
I created #37, which should make everything clearer for the reader. If #37 is accepted, then it the check is indeed redundant, that is we could remove it. (But we can also keep it, implementations are of course free to optimize it out).

**Comment by markblundeberg** [comment]
> If someone implements `x(R) != r` as `x(R) != r % p` (python notation) they may accept a signature with `r > p` which a correct implemention (without modulo in the inequality check) wouldn't have accepted.

Note that this ambiguity can be addressed by never converting `r` from its original bytes form, and just specifying a bytewise comparison (see #46, didn't realize this discussion was so closely related).

**Comment by real-or-random** [comment]
Right. Though that requires to serialize x(R), which is slower than parsing an integer (assuming optimized field arithmetic).

**Comment by markblundeberg** [comment]
> Right. Though that requires to serialize x(R), which is slower than parsing an integer (assuming optimized field arithmetic).

Hmm, but does the combination *(deserializing to field element, testing for field element equality)* have a lower cost than the combination *(serializing from field element, testing for bytewise equality)*?

My intuition was that these would be dominated by the second and first steps, respectively, and that field equality testing (negating, adding, then normalizing the result enough to compare to zero) would be slower than serializing (normalizing then extracting bytes).

**Comment by sipa** [comment]
Needs rebase.

**Comment by sipa** [comment]
Going to close this; I agree it's redundant when reading carefully, but being explicit does not hurt, and this makes it also clearer what sane inputs can be to the reader.

**Pull request closed without merging**
