### PR TITLE
Mention hash_type malleability would change wtxid

### PR DESCRIPTION
**Pull request by OrfeasLitos**
In footnote 12 of bip-taproot

### CODE REVIEW

**Comment by sipa** [comment]
Sure, but signing a second time with a different nonce would also change the wtxid. I don't mind mentioning this, but it seems unrelated to the sighash byte - whenever you replace a signature (which every signer can always do), the wtxid will change.

**Comment by OrfeasLitos** [comment]
I was thinking that if 65 byte `0x00` `hash_type` was allowed, the miner (or the publishing party) could also malleate the signature (of other parties) without the agreement of (the other) tx parties. This could be a problem for protocols that look at the `wtxid` instead of the `txid`.

Or would that kind of malleability be impossible?

**Comment by sipa** [comment]
Oh, of course. Maybe add "malleating (by third parties, including miners)" ?

**Review by jonasnick — APPROVED** [review]

**Comment by apoelstra** [comment]
I think this is a worthwhile change, but I'd be surprised to hear about protocols using wtxids in the wild.

**Comment by sipa** [comment]
ACK

**Pull request merged**
