### PR TITLE
lift_x returns a point, not a tuple

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
@nickler @real-or-random

**Comment by real-or-random** [comment]
I agree, that's somewhat weird.
 * Maybe we should then also have an explicit `Let P = (r, y).` line in `lift_x` to make the construction of a point more explicit, and then return P in the end.
 * Your suggestion somehow drops the information that -P is computed by negating y. Maybe
```
P = lift_x( ... )
If ...
    P' = (x(P), -y(P))
    Return P'
Return P
```

**Comment by sipa** [comment]
Is that necessary? We do plenty of EC operations already, and EC addition and multiplication aren't explained at that level of detail either.

**Comment by real-or-random** [comment]
Agreed.
(Now GitHub says you ant to merge 62 commit, maybe you screwed up your branch or there is again something wrong with GitHub here. No idea.).

**Comment by real-or-random** [comment]
Ah yeah, is it possible that you force-pushed bip-schnorr instead of bip-schnorr-patch? :D

**Comment by sipa** [comment]
Rebased.

**Comment by real-or-random** [comment]
ACK

**Comment by jnewbery** [comment]
ACK 7472c79283202ad9e40f2c912a3340d558921722

**Comment by sipa** [comment]
This doesn't really apply anymore after #55, but `lift_x` is now still defined as something returning a tuple, which is wrong.

**Comment by sipa** [comment]
Addressing this in #58.

**Pull request closed without merging**
