### PR TITLE
taproot/tapscript: remove a bunch of limits

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
As discussed on IRC,

* The 10000-byte limit doesn't accomplish much since it can be circumvented by splitting scripts up (all costs are linear in script size)
* The 201-non-push-opcode limit doesn't accomplish much, since the expensive non-push opcodes are only sig checks and hashes...
* ...and signatures are covered by the sigops ratio limit, while
* hashes appear to be roughly as costly, per byte, as sigops (once the ratio limit is considered, which forces every sigop to include 50 wu of material)
* Also, the non-ratio limits make composing of (mini)scripts difficult
* Also, having multiple limits means that script creation is a multidimensional problem

Finally,
* This PR removes the 32-depth limit from taproot, but as discussed we may want to reinstate this (though 32 is probably too low).

**Comment by ajtowns** [comment]
I think if you had more than 201 DUP opcodes it could become expensive in terms of memory allocations.

Could fix that by replacing it with a stack size limit, but I'm not sure how you'd actually do that sanely. Maybe a stack memory usage limit something like `sum(size(element[i])) <= 2*k+1024` where k is the serialised size of the original witness script and witness stack?

Not sure if some limit along those lines would be easier or harder to analyse than the 201-non-push opcode limit.

I think upping the 32-depth limit to 256 makes sense. If you want to spam data to the blockchain, this gives you about 1kB (32-depth limit), 8kB (256-depth limit), 400kB (tx size standardness), or 4MB (miner limit). I feel a bit like 8kB is a fair bit less risky than 400kB?

Concept ack otherwise.

**Comment by ajtowns** [comment]
JFTR, I agree with sipa's suggestions. If I were picking a tree depth limit I'd probably go with 80 or 128, I think, since they're "round" and filling either should be pretty impractical, but agree that anything between 64-256 seems reasonable.

**Comment by sipa** [comment]
A more elaborate version: #73.

**Comment by apoelstra** [comment]
Superseded by #73

**Pull request closed without merging**
