### PR TITLE
Prescribe that an output key should always have a taproot commitment

### PR DESCRIPTION
**Pull request by jonasnick**
Afaik @apoelstra came up with this attack. Mitigating this by adding an unspendable script path was suggested by @real-or-random.

### CODE REVIEW

**Comment by jonasnick** [comment]
Alternatively, we can prescribe the mitigation in this PR: *never* create a taproot output key without a script spending path in a multi party context and instead *always* add an unspendable script spending path.

**Comment by real-or-random** [comment]
I think prescribing it is the safer and simpler approach.

**Comment by sipa** [comment]
I prefer prescribing that Taproot outputs must always be constructed using an unspendable script if no script paths are desirable.

**Comment by jonasnick** [comment]
Adjusted the PR accordingly.

**Comment by real-or-random** [comment]
ack

**Pull request merged**
