### PR TITLE
Extend codeseparator_position and input_index from 16 to 32 bits

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
As suggested by @roconnor_blockstream.

**Comment by roconnor-blockstream** [comment]
My suggestion was to extend `input_index` from 16 to 32 bits in bip-taproot, but codeseparator_position ought to be changed as well.  Both are directly subject to the MAX_SIZE = 0x02000000 limit.

**Comment by sipa** [comment]
Ah, good point, I misremembered.

**Comment by ajtowns** [comment]
iirc having a bigger `input_index` field is helpful for non-bitcoin-blockchain things like proof of reserves, or needing fewer changes if we get a blocksize increase? seems sensible to me.

ack on bumping codesep_pos now scripts aren't limited to <65kB.

**Pull request merged**
