### PR TITLE
Be more pedantic about key spend signatures

### PR DESCRIPTION
**Pull request by instagibbs**
This immediately follows a "script" branch section which threw me off the very first time I read it since I was still in "script" mode.

### CODE REVIEW

**Comment by jonasnick** [comment]
This PR doesn't work as is because the section actually applies to both key and script path spends;  bip-tapscript signature opcodes use the same signature validation. In the  section in the `Rules for signature opcodes"`: `"the signature is validated according to the bip-tap root signing validation rules against the public key and the tapscript transaction digest (to be defined hereinafter) as message."` It's a bit annoying that it ended up that way.

**Comment by sipa** [comment]
This is also related to #99, which suggests abstracting out the message function in bip-taproot, and then invoking it both from bip-taproot and bip-tapscript, rather than "patching" the function in bip-tapscript.

**Comment by instagibbs** [comment]
Hmmm, there has to be a better way to format this.

**Comment by sipa** [comment]
Let's revisit this after #99 is resolved.

**Pull request closed without merging**
