### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by fametrano**

### CODE REVIEW

**Comment by real-or-random** [comment]
ACK, but obviously depends on the outcome of #28 .

**Comment by fametrano** [comment]
This is actually fixing two typos: the first one should be fixed whatever the outcome on #28

**Comment by fametrano** [comment]
there was a 3rd instance of r_i that eluded me the first time

**Comment by fametrano** [comment]
there were more instances of the same typo that eluded me the first time around

**Comment by real-or-random** [comment]
Wait no, all of this is not necessary. The scope of `r` is just the loop, this is fine as it is.

**Comment by fametrano** [comment]
Oh my...

**Pull request closed without merging**
