### PR TITLE
more precise wording: limits on tx+block size -> block weight limit

### PR DESCRIPTION
**Pull request by stefanwouldgo**
IIRC, there is no block size limit post-Segwit

### CODE REVIEW

**Comment by gmaxwell** [comment]
There is no consensus transaction size limit currently in Bitcoin, just weight. So I think this revision can be simplified further by saying implicitly limited by block weight.

**Comment by sipa** [comment]
Needs trivial rebase.

**Comment by flack** [comment]
"limited by the block weight" sounds a bit unclear. Shouldn't it rather be "limited by the block weight limit" (or similar)?

**Comment by stefanwouldgo** [comment]
> "limited by the block weight" sounds a bit unclear. Shouldn't it rather be "limited by the block weight limit" (or similar)?

I prefer the ellipsis here to repetition of  "limit". Do you really think it's unclear what is meant? Any other opinions?

**Comment by flack** [comment]
Yeah, stylistically is nicer not to repeat the word "limit", but since this is a technical document, there's probably some value in leaving as little room for misinterpretation as possible. Anyway, I just wanted to highlight that this is changed here, too, not only blocksize => blockweight as the PR title suggests

**Comment by stefanwouldgo** [comment]
How about "implicitly bounded by the block weight limit"?

**Comment by flack** [comment]
sgtm

**Pull request merged**
